### ISSUE TITLE
[2013-10-09-dns] [Add Content] Request Feature~

### ISSUE THREAD

**Issue by zkteh** [garyng/garyng.github.io#1]
求加入 ipv6 DNS IP
求加入 ipconfig /flushdns （router 也需要 clear dns cache，重启 router）
相关的 error message :
dns_probe_finished_bad_config
dns_probe_started
求加入 直接在 router 设定 DNS
求加入解释 DNS
求加入 可能发现的情况？kat.ph // twitter //  kanxi123 // fb // google services

**Comment by garyng** [comment]
@zkteh 
请求加入更加详细资料（解释要加入的.. 因为我看不懂 xD）

**Comment by garyng** [comment]
可另开新帖子
